#
# Docker Ubuntu Focal image to build Yocto 3.3
#

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Keep the dependency list as short as reasonable
RUN apt-get update && \
    apt-get install -y bc bison bsdmainutils build-essential cmake curl locales \
        flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev \
        lib32z1-dev libncurses5-dev git-lfs \
        libsdl1.2-dev libxkbcommon-x11-0 libwayland-cursor0 libxml2-utils lzop \
        openjdk-8-jdk lzop wget git-core unzip \
        genisoimage sudo socat xterm gawk cpio texinfo \
        gettext vim diffstat chrpath rsync lz4 zstd \
        python-mako python-is-python3 libusb-1.0-0-dev exuberant-ctags \
        pngcrush schedtool xsltproc zip zlib1g-dev libswitch-perl tree \
	uuid-runtime grub-common liblz4-tool && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD https://commondatastorage.googleapis.com/git-repo-downloads/repo /usr/local/bin/
RUN chmod 755 /usr/local/bin/*

# ===== create user/setup environment =====
RUN useradd --create-home --shell /bin/bash --groups sudo compulab
RUN echo "compulab ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/compulab
RUN echo "[color]\n\tui = false\n[user]\n\tname = compulab\n\temail = compulab@CompuLab.com" > /home/compulab/.gitconfig && \
	chown compulab:compulab /home/compulab/.gitconfig && \
	chmod 0644 /home/compulab/.gitconfig

# Improve rebuild performance by enabling compiler cache
ENV USE_CCACHE 1
ENV CCACHE_DIR /home/compulab/.ccache

# some QT-Apps/Gazebo do not show controls without this
ENV QT_X11_NO_MITSHM 1

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
 
ENV HOME /home/compulab
ENV USER compulab
USER compulab

# build environment
WORKDIR /work
